# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - curl -sSL "https://raw.githubusercontent.com/h5bp-bot/scripts/0.4.0/update_site_branch.sh" |
      bash /dev/stdin "dist" "server-content" "Hey server, this content is for you! [skip ci]"

before_script:
  - travis_retry npm install -g grunt-cli

env:
  global:
    - secure: "QWK+gElKfZ+lNo0fvKAbiBr8fShLylHUWZxireWKwDrt+fQ87AFY7DFpXRzdJPZXuzxBB6XpAgPC2xH1hnctBx3OQXWIOWzQSbhMpOzoxE8S/keM9ckYBZAAFFs8tfP3Kz1zFFuiEbhpOlKCSzq73GLJMVd0enUJkP0RJu3pwyU="

git:
  depth: 10

language: node_js

node_js:
  - "0.10"
