# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

after_success:
  - curl -sSL "https://raw.githubusercontent.com/h5bp-bot/scripts/0.2.0/update_site_branch.sh" |
      bash /dev/stdin "dist" "server-content" "Hey server, this content is for you!"

before_script:
  - travis_retry npm install -g grunt-cli

branches:
  except:
    - server-content

env:
  global:
    - secure: "LisKONLxvtug/s7/5opPKGV54qQfmqExQk3u0XYODhJeKQwGv7+pp9eHA7YLe5wJofcQpO9MlQQi+EqH/jp0SnywFdl+AuuJfU1E1W/QxNmYOIPY8ZoADBi97hodtfP+yWAuK/9JxZJpXro1B/7nhEAq4zfpj1BNetKFxpE7L80="

git:
  depth: 10

language: node_js

node_js:
  - "0.10"
