# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

before_script:
  - travis_retry npm install -g grunt-cli

branches:
  except:
    - server-content

git:
  depth: 10

language: node_js

node_js:
  - "0.10"
